"""init

Revision ID: 0bf7c21a577c
Revises: 
Create Date: 2025-11-21 15:42:31.870003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0bf7c21a577c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenblacklist_id'), 'tokenblacklist', ['id'], unique=False)
    op.create_index(op.f('ix_tokenblacklist_token'), 'tokenblacklist', ['token'], unique=True)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('housing_size', sa.Integer(), nullable=False),
    sa.Column('budget_pref', sa.Float(), nullable=False),
    sa.Column('dietary_pref', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('dietary_restrictions', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('inventoryitem',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('expiration_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryitem_id'), 'inventoryitem', ['id'], unique=False)
    op.create_table('mealplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('target_budget', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplan_id'), 'mealplan', ['id'], unique=False)
    op.create_table('foodlog',
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('consumed_at', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventoryitem.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodlog_id'), 'foodlog', ['id'], unique=False)
    op.create_table('mealplanitem',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('food_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('uses_inventory', sa.Boolean(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['mealplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplanitem_id'), 'mealplanitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplanitem_id'), table_name='mealplanitem')
    op.drop_table('mealplanitem')
    op.drop_index(op.f('ix_foodlog_id'), table_name='foodlog')
    op.drop_table('foodlog')
    op.drop_index(op.f('ix_mealplan_id'), table_name='mealplan')
    op.drop_table('mealplan')
    op.drop_index(op.f('ix_inventoryitem_id'), table_name='inventoryitem')
    op.drop_table('inventoryitem')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tokenblacklist_token'), table_name='tokenblacklist')
    op.drop_index(op.f('ix_tokenblacklist_id'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###
