"""add_meal_plans_tables

Revision ID: 33ad4d37c229
Revises: ae09b78c09da
Create Date: 2025-11-21 09:42:53.562485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33ad4d37c229'
down_revision: Union[str, Sequence[str], None] = 'ae09b78c09da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mealplan',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('target_budget', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplan_id'), 'mealplan', ['id'], unique=False)
    op.create_table('mealplanitem',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('food_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('uses_inventory', sa.Boolean(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['mealplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mealplanitem_id'), 'mealplanitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mealplanitem_id'), table_name='mealplanitem')
    op.drop_table('mealplanitem')
    op.drop_index(op.f('ix_mealplan_id'), table_name='mealplan')
    op.drop_table('mealplan')
    # ### end Alembic commands ###
