"""add_inventory_link_to_food_logs

Revision ID: ae09b78c09da
Revises: 8a0b01894f15
Create Date: 2025-11-21 00:23:40.429392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae09b78c09da'
down_revision: Union[str, Sequence[str], None] = '8a0b01894f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodlog', sa.Column('inventory_item_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'foodlog', 'inventoryitem', ['inventory_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foodlog', type_='foreignkey')
    op.drop_column('foodlog', 'inventory_item_id')
    # ### end Alembic commands ###
