"""inventory update

Revision ID: b9852d4b5b75
Revises: 7e93f4466c91
Create Date: 2025-11-20 22:36:52.186968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9852d4b5b75'
down_revision: Union[str, Sequence[str], None] = '7e93f4466c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventoryitem', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('inventoryitem_user_id_fkey'), 'inventoryitem', type_='foreignkey')
    op.create_foreign_key(None, 'inventoryitem', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.create_foreign_key(op.f('inventoryitem_user_id_fkey'), 'inventoryitem', 'user', ['user_id'], ['id'])
    op.alter_column('inventoryitem', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
